jobs:
  include:
  - os: linux
    dist: xenial
  - os: linux
    arch: arm64
    dist: xenial 

before_script:
  - export VASIL_DEBUG=true
  - ${SHELL} --version
  - echo --version
  - grep --version
  - sed --version
  - sort --version
  - uniq --version

script:
  - $SHELL vasil.sh; result="$?"; if [ "${result}" -ne 1 ];then exit 1;fi
  - $SHELL vasil.sh non-existing-file.html; result="$?"; if [ "${result}" -ne 2 ];then exit 2;fi
  - $SHELL vasil.sh README.md; result="$?"; if [ "${result}" -ne 3 ];then exit 3;fi
  - $SHELL vasil.sh test/sample.html; result=$?; if [ "${result}" -ne 5 ];then exit 4;fi
